# Andrew Vaughan DevOps Infrastructure Playbook
#
# See `README.md#Usage` for information on how to run this Ansible Playbook.
#
# @author Andrew Vaughan <hello@andrewvaughan.io>
# @since  0.1.0
---

#
# @TODO - Ensure python2 is installed on the remote system with Ansible `raw` as a pre-task
#


#
# Configure the server to the expected base standard, including security and performance needs
#
- name         : Launching "common" Tasks
  hosts        : hosted
  gather_facts : false
  roles:
    - { role : common, tags : [ "common" ] }
